# Generated by Django 4.2.3 on 2023-07-07 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 15, 34, 0, 530260, tzinfo=datetime.timezone.utc)),
        ),
    ]
