# Generated by Django 4.2.3 on 2023-07-10 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 18, 6, 35, 796023, tzinfo=datetime.timezone.utc)),
        ),
    ]
